"""Fix backref

Revision ID: 036f90a0c9f0
Revises: 8bd59ea1aa33
Create Date: 2023-06-04 17:58:03.104913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036f90a0c9f0'
down_revision = '8bd59ea1aa33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
