"""Fix cascading constraint again

Revision ID: 07ad0f4ff89e
Revises: 0a7344a58ce8
Create Date: 2023-06-04 10:07:10.475907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ad0f4ff89e'
down_revision = '0a7344a58ce8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
