"""Fix cascading constraint

Revision ID: 0a7344a58ce8
Revises: f822ab1c6bd6
Create Date: 2023-06-04 09:57:36.045644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7344a58ce8'
down_revision = 'f822ab1c6bd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
