"""Fix cascading constraint again

Revision ID: 8bd59ea1aa33
Revises: 07ad0f4ff89e
Create Date: 2023-06-04 17:55:03.039843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd59ea1aa33'
down_revision = '07ad0f4ff89e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
